apiVersion: v1
kind: Service
metadata:
  name: backend-service #front access http://backend-sevice
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 3000 #!!
    targetPort: 3000
  type: ClusterIP
